### ISSUE TITLE
GCC 10.0.1 build failure

### ISSUE THREAD

**Issue by xvitaly** [kiwix/kiwix-lib#317]
Failed to build kiwix-lib with GCC 10.0.1 from Fedora 32:

```c++
[12/41] c++ -Isrc/25a6634@@kiwix@sha -Isrc -I../src -Iinclude -I../include -Istatic -I/usr/include/p11-kit-1 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=c++11 -O2 -g -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -pthread -MD -MQ 'src/25a6634@@kiwix@sha/downloader.cpp.o' -MF 'src/25a6634@@kiwix@sha/downloader.cpp.o.d' -o 'src/25a6634@@kiwix@sha/downloader.cpp.o' -c ../src/downloader.cpp
FAILED: src/25a6634@@kiwix@sha/downloader.cpp.o 
c++ -Isrc/25a6634@@kiwix@sha -Isrc -I../src -Iinclude -I../include -Istatic -I/usr/include/p11-kit-1 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=c++11 -O2 -g -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -pthread -MD -MQ 'src/25a6634@@kiwix@sha/downloader.cpp.o' -MF 'src/25a6634@@kiwix@sha/downloader.cpp.o.d' -o 'src/25a6634@@kiwix@sha/downloader.cpp.o' -c ../src/downloader.cpp
In file included from ../src/downloader.cpp:20:
../include/downloader.h:40:45: error: expected class-name before '{' token
   40 | class AriaError : public std::runtime_error {
      |                                             ^
../include/downloader.h: In constructor 'kiwix::AriaError::AriaError(const string&)':
../include/downloader.h:42:61: error: expected class-name before '(' token
   42 |   AriaError(const std::string& message) : std::runtime_error(message) {}
      |                                                             ^
../include/downloader.h:42:61: error: expected '{' before '(' token
```

Full build log: https://kojipkgs.fedoraproject.org//work/tasks/4395/41184395/build.log

**Comment by kelson42** [comment]
It compiles well with version 9.2.1.

**Comment by xvitaly** [comment]
> It compiles well with version 9.2.1.

Yes, but fails with GCC 10.0.1.

**Comment by kelson42** [comment]
@xvitaly Yes, there is a bug in gcc 10 (not yet officially released) or in our code.

**Comment by xvitaly** [comment]
> Yes, there is a bug in gcc 10 (not yet officially released) or in our code.

In code.

**Comment by kelson42** [comment]
> > Yes, there is a bug in gcc 10 (not yet officially released) or in our code.
> 
> In code.

Great you know the answer! Would you be able to make a PR?

**Comment by kelson42** [comment]
@xvitaly If you just add `#include <stdexcept>` beside the other includes in `downloader.h`, does it works?

**Comment by xvitaly** [comment]
> Great you know the answer! Would you be able to make a PR?

OK.

> If you just add #include <stdexcept> beside the other includes in downloader.h, does it works?

Will check it.

**Comment by xvitaly** [comment]
Yes, it fixed issue, but some other cpp files need to be patched too:

```c++
../src/tools/regexTools.cpp: In function 'std::unique_ptr<icu_65::RegexMatcher> buildMatcher(const string&, icu_65::UnicodeString&)':
../src/tools/regexTools.cpp:39:17: error: 'out_of_range' in namespace 'std' does not name a type
   39 |   } catch (std::out_of_range&) {
      |                 ^~~~~~~~~~~~
../src/tools/regexTools.cpp:44:19: error: 'out_of_range' in namespace 'std' does not name a type
   44 |     } catch (std::out_of_range&) {
      |                   ^~~~~~~~~~~~
```

**Comment by xvitaly** [comment]
After patching `regexTools.cpp` now it builds well. Thanks.

```patch
--- a/src/tools/regexTools.cpp
+++ b/src/tools/regexTools.cpp
@@ -25,6 +25,7 @@
 
 #include <memory>
 #include <map>
+#include <stdexcept>
 #include <pthread.h>
 
 std::map<std::string, std::shared_ptr<icu::RegexPattern>> regexCache;
```
